package labs_examples.exception_handling.labs;

/**
 * Exception Handling Exercise 2:
 *
 *      Demonstrate a try/catch with multiple catch statements.
 *      try{
 *          // block of code to monitor for errors
 *        } catch (Exception one){
 *          // handle for Exception one
 *        } catch (Exception two){
 *           // handle for Exception two
 *        }
 *
 *
 */



